In [7]:
import pandas as pd
from glob import glob

In [8]:
filepaths = glob('20210106_Python_Excel_01/source/*.xlsx')
filepaths

['20210106_Python_Excel_01/source/請求書_12月_株式会社ABC.xlsx',
 '20210106_Python_Excel_01/source/請求書_10月_TTTInc.xlsx',
 '20210106_Python_Excel_01/source/請求書_11月_XYZ株式会社.xlsx']

In [26]:
filepath = filepaths[0]

In [27]:
filepath

'20210106_Python_Excel_01/source/請求書_12月_株式会社ABC.xlsx'

In [28]:
_df = pd.read_excel(filepath)
_df.head(15)

,請求書,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,株式会社ABC,NaN,NaN,NaN,NaN,御中,NaN,NaN,NaN,NaN,NaN,伝票No.：,003,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,発行日：,2020/12/28,NaN,NaN,NaN,NaN,NaN,0.1
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,担当者名：,桜田,5.0,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,税込み金額,NaN,NaN,66110.0,NaN,NaN,NaN,（税込）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,下記の通り、ご請求申し上げます。,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,No.,日付,商品コード,NaN,品名,NaN,NaN,備考,NaN,NaN,数量[L] or [-],単価[¥/L] or [¥],NaN,NaN,金額,NaN,NaN,NaN,NaN
11,1,2020-12-01 00:00:00,GSL0001,NaN,レギュラー,NaN,NaN,NaN,NaN,NaN,20,120,NaN,NaN,2400,NaN,NaN,NaN,NaN
12,2,2020-12-05 00:00:00,GSL0002,NaN,ハイオク,NaN,NaN,NaN,NaN,NaN,45,160,NaN,NaN,7200,NaN,NaN,NaN,NaN
13,3,2020-12-07 00:00:00,GSL0003,NaN,軽油,NaN,NaN,NaN,NaN,NaN,50,100,NaN,NaN,5000,NaN,NaN,NaN,NaN
14,4,2020-12-08 00:00:00,GSL0004,NaN,灯油,NaN,NaN,携行缶,NaN,NaN,30,80,NaN,NaN,2400,NaN,NaN,NaN,NaN

In [29]:
columns = _df.iloc[10, [1, 2, 4, 10, 11, 14]]
columns

Unnamed: 1                 日付
Unnamed: 2              商品コード
Unnamed: 4                 品名
Unnamed: 10      数量[L] or [-]
Unnamed: 11    単価[¥/L] or [¥]
Unnamed: 14                金額
Name: 10, dtype: object

In [30]:
df = _df.iloc[11:23, [1, 2, 4, 10, 11, 14]]

In [31]:
df.columns = columns

In [32]:
df

10                   日付    商品コード     品名 数量[L] or [-] 単価[¥/L] or [¥]     金額
11  2020-12-01 00:00:00  GSL0001  レギュラー           20            120   2400
12  2020-12-05 00:00:00  GSL0002   ハイオク           45            160   7200
13  2020-12-07 00:00:00  GSL0003     軽油           50            100   5000
14  2020-12-08 00:00:00  GSL0004     灯油           30             80   2400
15  2020-12-11 00:00:00  CMT0001   洗車 A            1            500    500
16  2020-12-15 00:00:00  CMT0002   洗車 B            1           1500   1500
17  2020-12-18 00:00:00  CMT0003   洗車 C            1           3000   3000
18  2020-12-20 00:00:00  CMT0004  オイル交換            1           1000   1000
19  2020-12-22 00:00:00  CMT0005  タイヤ交換            1           4000   4000
20  2020-12-22 00:00:00  GDS0001    タイヤ            4           8000  32000
21  2020-12-22 00:00:00  GDS0002    コロン            1            800    800
22  2020-12-22 00:00:00  GDS0003   スナック            3            100    300

In [33]:
df['企業名'] = _df.iloc[2, 0]

In [34]:
df.head()

10,日付,商品コード,品名,数量[L] or [-],単価[¥/L] or [¥],金額,企業名
11,2020-12-01 00:00:00,GSL0001,レギュラー,20,120,2400,株式会社ABC
12,2020-12-05 00:00:00,GSL0002,ハイオク,45,160,7200,株式会社ABC
13,2020-12-07 00:00:00,GSL0003,軽油,50,100,5000,株式会社ABC
14,2020-12-08 00:00:00,GSL0004,灯油,30,80,2400,株式会社ABC
15,2020-12-11 00:00:00,CMT0001,洗車 A,1,500,500,株式会社ABC

In [35]:
df['企業コード'] = _df.iloc[3, 4]
df['請求書No'] = _df.iloc[2, 12]
df['発行日'] = _df.iloc[3, 12]
df['発行者'] = _df.iloc[4, 12]
df['発行者コード'] = _df.iloc[4, 13]

In [36]:
df.head()

10,日付,商品コード,品名,数量[L] or [-],単価[¥/L] or [¥],金額,企業名,企業コード,請求書No,発行日,発行者,発行者コード
11,2020-12-01 00:00:00,GSL0001,レギュラー,20,120,2400,株式会社ABC,6,003,2020/12/28,桜田,5.0
12,2020-12-05 00:00:00,GSL0002,ハイオク,45,160,7200,株式会社ABC,6,003,2020/12/28,桜田,5.0
13,2020-12-07 00:00:00,GSL0003,軽油,50,100,5000,株式会社ABC,6,003,2020/12/28,桜田,5.0
14,2020-12-08 00:00:00,GSL0004,灯油,30,80,2400,株式会社ABC,6,003,2020/12/28,桜田,5.0
15,2020-12-11 00:00:00,CMT0001,洗車 A,1,500,500,株式会社ABC,6,003,2020/12/28,桜田,5.0

In [59]:
def extract(filepath):
    _df = pd.read_excel(filepath)
    columns = _df.iloc[10, [1, 2, 4, 10, 11, 14]]
    df = _df.iloc[11:23, [1, 2, 4, 10, 11, 14]]
    df.columns = columns
    df['企業名'] = _df.iloc[2, 0]
    df['企業コード'] = _df.iloc[3, 4]
    df['請求書No'] = _df.iloc[2, 12]
    df['発行日'] = _df.iloc[3, 12]
    df['発行者'] = _df.iloc[4, 12]
    df['発行者コード'] = _df.iloc[4, 13]
    return df

In [60]:
df = extract(filepath)
df.head()

10,日付,商品コード,品名,数量[L] or [-],単価[¥/L] or [¥],金額,企業名,企業コード,請求書No,発行日,発行者,発行者コード
11,2020-11-01 00:00:00,GSL0001,レギュラー,20,120,2400,XYZ株式会社,6,008,2020/11/30,山岡,8.0
12,2020-11-02 00:00:00,GSL0002,ハイオク,45,160,7200,XYZ株式会社,6,008,2020/11/30,山岡,8.0
13,2020-11-05 00:00:00,GSL0003,軽油,50,100,5000,XYZ株式会社,6,008,2020/11/30,山岡,8.0
14,2020-11-10 00:00:00,GSL0004,灯油,30,80,2400,XYZ株式会社,6,008,2020/11/30,山岡,8.0
15,2020-11-11 00:00:00,GSL0001,レギュラー,30,120,3600,XYZ株式会社,6,008,2020/11/30,山岡,8.0

In [61]:
sample_1 = pd.DataFrame([[1, 2, 3],[4, 5, 6]])
sample_2 = pd.DataFrame([[-1, 0, 2],[8, 4, 9]])

In [62]:
sample_2

   0  1  2
0 -1  0  2
1  8  4  9

In [63]:
pd.concat([sample_1, sample_2])

   0  1  2
0  1  2  3
1  4  5  6
0 -1  0  2
1  8  4  9

In [64]:
pd.concat([sample_1, sample_2], axis=1)

   0  1  2  0  1  2
0  1  2  3 -1  0  2
1  4  5  6  8  4  9

In [65]:
df = pd.DataFrame()

for filepath in filepaths:
    _df = extract(filepath)
    df = pd.concat([df, _df])

In [66]:
df

10,日付,商品コード,品名,数量[L] or [-],単価[¥/L] or [¥],金額,企業名,企業コード,請求書No,発行日,発行者,発行者コード
11,2020-12-01 00:00:00,GSL0001,レギュラー,20,120,2400,株式会社ABC,6,003,2020/12/28,桜田,5.0
12,2020-12-05 00:00:00,GSL0002,ハイオク,45,160,7200,株式会社ABC,6,003,2020/12/28,桜田,5.0
13,2020-12-07 00:00:00,GSL0003,軽油,50,100,5000,株式会社ABC,6,003,2020/12/28,桜田,5.0
14,2020-12-08 00:00:00,GSL0004,灯油,30,80,2400,株式会社ABC,6,003,2020/12/28,桜田,5.0
15,2020-12-11 00:00:00,CMT0001,洗車 A,1,500,500,株式会社ABC,6,003,2020/12/28,桜田,5.0
16,2020-12-15 00:00:00,CMT0002,洗車 B,1,1500,1500,株式会社ABC,6,003,2020/12/28,桜田,5.0
17,2020-12-18 00:00:00,CMT0003,洗車 C,1,3000,3000,株式会社ABC,6,003,2020/12/28,桜田,5.0
18,2020-12-20 00:00:00,CMT0004,オイル交換,1,1000,1000,株式会社ABC,6,003,2020/12/28,桜田,5.0
19,2020-12-22 00:00:00,CMT0005,タイヤ交換,1,4000,4000,株式会社ABC,6,003,2020/12/28,桜田,5.0
20,2020-12-22 00:00:00,GDS0001,タイヤ,4,8000,32000,株式会社ABC,6,003,2020/12/28,桜田,5.0
21,2020-12-22 00:00:00,GDS0002,コロン,1,800,800,株式会社ABC,6,003,2020/12/28,桜田,5.0
22,2020-12-22 00:00:00,GDS0003,スナック,3,100,300,株式会社ABC,6,003,2020/12/28,桜田,5.0
11,2020-10-04 00:00:00,GSL0001,レギュラー,20,120,2400,TTT Inc.,6,012,2020/10/31,岸辺,2.0
12,2020-10-05 00:00:00,GSL0002,ハイオク,45,160,7200,TTT Inc.,6,012,2020/10/31,岸辺,2.0
13,2020-10-06 00:00:00,GSL0003,軽油,50,100,5000,TTT Inc.,6,012,2020/10/31,岸辺,2.0
14,2020-10-07 00:00:00,GSL0002,ハイオク,45,160,7200,TTT Inc.,6,012,2020/10/31,岸辺,2.0
15,2020-10-08 00:00:00,GSL0003,軽油,50,100,5000,TTT Inc.,6,012,2020/10/31,岸辺,2.0
16,2020-10-09 00:00:00,CMT0002,洗車 B,1,1500,1500,TTT Inc.,6,012,2020/10/31,岸辺,2.0
17,2020-10-10 00:00:00,GSL0003,軽油,50,100,5000,TTT Inc.,6,012,2020/10/31,岸辺,2.0
18,2020-10-11 00:00:00,GSL0002,ハイオク,40,160,6400,TTT Inc.,6,012,2020/10/31,岸辺,2.0
19,2020-10-12 00:00:00,GSL0002,ハイオク,30,160,4800,TTT Inc.,6,012,2020/10/31,岸辺,2.0
20,2020-10-13 00:00:00,GSL0003,軽油,50,100,5000,TTT Inc.,6,012,2020/10/31,岸辺,2.0
21,2020-10-14 00:00:00,GSL0003,軽油,50,100,5000,TTT Inc.,6,012,2020/10/31,岸辺,2.0
22,NaN,NaN,NaN,NaN,NaN,0,TTT Inc.,6,012,2020/10/31,岸辺,2.0
11,2020-11-01 00:00:00,GSL0001,レギュラー,20,120,2400,XYZ株式会社,6,008,2020/11/30,山岡,8.0
12,2020-11-02 00:00:00,GSL0002,ハイオク,45,160,7200,XYZ株式会社,6,008,2020/11/30,山岡,8.0
13,2020-11-05 00:00:00,GSL0003,軽油,50,100,5000,XYZ株式会社,6,008,2020/11/30,山岡,8.0
14,2020-11-10 00:00:00,GSL0004,灯油,30,80,2400,XYZ株式会社,6,008,2020/11/30,山岡,8.0
15,2020-11-11 00:00:00,GSL0001,レギュラー,30,120,3600,XYZ株式会社,6,008,2020/11/30,山岡,8.0
16,2020-11-12 00:00:00,GSL0002,ハイオク,30,160,4800,XYZ株式会社,6,008,2020/11/30,山岡,8.0
17,2020-11-13 00:00:00,CMT0003,洗車 C,1,3000,3000,XYZ株式会社,6,008,2020/11/30,山岡,8.0
18,2020-11-20 00:00:00,GSL0004,灯油,15,80,1200,XYZ株式会社,6,008,2020/11/30,山岡,8.0
19,2020-11-23 00:00:00,CMT0003,洗車 C,1,3000,3000,XYZ株式会社,6,008,2020/11/30,山岡,8.0
20,2020-11-25 00:00:00,GSL0004,灯油,40,80,3200,XYZ株式会社,6,008,2020/11/30,山岡,8.0
21,NaN,NaN,NaN,NaN,NaN,0,XYZ株式会社,6,008,2020/11/30,山岡,8.0
22,NaN,NaN,NaN,NaN,NaN,0,XYZ株式会社,6,008,2020/11/30,山岡,8.0

In [67]:
df = df.dropna()

In [68]:
df.tail()

10,日付,商品コード,品名,数量[L] or [-],単価[¥/L] or [¥],金額,企業名,企業コード,請求書No,発行日,発行者,発行者コード
16,2020-11-12 00:00:00,GSL0002,ハイオク,30,160,4800,XYZ株式会社,6,008,2020/11/30,山岡,8.0
17,2020-11-13 00:00:00,CMT0003,洗車 C,1,3000,3000,XYZ株式会社,6,008,2020/11/30,山岡,8.0
18,2020-11-20 00:00:00,GSL0004,灯油,15,80,1200,XYZ株式会社,6,008,2020/11/30,山岡,8.0
19,2020-11-23 00:00:00,CMT0003,洗車 C,1,3000,3000,XYZ株式会社,6,008,2020/11/30,山岡,8.0
20,2020-11-25 00:00:00,GSL0004,灯油,40,80,3200,XYZ株式会社,6,008,2020/11/30,山岡,8.0

In [70]:
df = df.iloc[:, [6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5]]

In [71]:
df.to_excel('20210106_Python_Excel_01/output/all_data.xlsx', index=False)